/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#43485d",
        "surface-dim": "#0b1326",
        "on-background": "#dae2fd",
        "surface-variant": "#2d3449",
        "on-secondary-container": "#b2b7d0",
        "primary-container": "#d4af37",
        "on-tertiary-fixed": "#211b00",
        "on-secondary": "#2a3043",
        "surface-container-lowest": "#060e20",
        "surface-tint": "#e9c349",
        "on-tertiary": "#383007",
        "primary-fixed-dim": "#e9c349",
        "inverse-surface": "#dae2fd",
        "on-tertiary-fixed-variant": "#50471c",
        "tertiary-fixed-dim": "#d4c690",
        "surface": "#0b1326",
        "on-secondary-fixed-variant": "#40465a",
        "on-primary-fixed": "#241a00",
        "secondary-fixed-dim": "#c0c6de",
        "on-error": "#690005",
        "inverse-on-surface": "#283044",
        "on-primary-container": "#554300",
        "inverse-primary": "#735c00",
        "tertiary-fixed": "#f1e2aa",
        "secondary": "#c0c6de",
        "tertiary-container": "#c0b37e",
        "surface-container-low": "#131b2e",
        "on-surface-variant": "#d0c5af",
        "on-error-container": "#ffdad6",
        "tertiary": "#ddce97",
        "on-primary-fixed-variant": "#574500",
        "surface-bright": "#31394d",
        "secondary-fixed": "#dce1fb",
        "on-surface": "#dae2fd",
        "surface-container-highest": "#2d3449",
        "error-container": "#93000a",
        "outline-variant": "#4d4635",
        "on-primary": "#3c2f00",
        "primary": "#f2ca50",
        "background": "#0b1326",
        "surface-container": "#171f33",
        "on-tertiary-container": "#4e451b",
        "error": "#ffb4ab",
        "outline": "#99907c",
        "on-secondary-fixed": "#151b2d",
        "surface-container-high": "#222a3d",
        "primary-fixed": "#ffe088",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1440px",
        "margin-page": "64px",
        "section-gap": "120px",
        unit: "8px",
      },
      fontFamily: {
        "body-lg": ["Manrope"],
        "display-xl": ["Newsreader"],
        "body-md": ["Manrope"],
        "headline-md": ["Newsreader"],
        "headline-lg": ["Newsreader"],
        "label-sm": ["Manrope"],
      },
      fontSize: {
        "body-lg": ["1.125rem", { lineHeight: "1.6", fontWeight: "400" }],
        "display-xl": ["4rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "300" }],
        "body-md": ["1rem", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["1.75rem", { lineHeight: "1.3", fontWeight: "400" }],
        "headline-lg": ["2.5rem", { lineHeight: "1.2", fontWeight: "400" }],
        "label-sm": ["0.75rem", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;